app_debug: true

mysql:
  #  地址
  hostname: localhost
  # 端口
  port: 3306
  # 用户名
  user: root
  # 密码
  password: bendimima
  # 数据库
  database: go-pure

redis:
  hostname: localhost
  port: 6379
  user:
  password:
  database: 0

# 漏桶配置
rate:
  enable: true
  limit: 500
  burst: 100

# rabbitmq
rmq:
  user: "mongielee"
  password: "123456"
  host: "127.0.0.1"
  port: "5672"
  virtual_host: "fuckHost"